# Generated by Django 5.1.3 on 2024-12-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_verification_token'),
    ]

    operations = [
    ]
