# Generated by Django 5.1.3 on 2024-12-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_populate_verification_tokens'),
        ('table1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='accounts.user'),
        ),
    ]
