# Generated by Django 5.1.3 on 2024-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_task', models.CharField(max_length=200)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
            ],
        ),
    ]
