# Generated by Django 5.1.3 on 2024-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='etat',
            field=models.CharField(max_length=50),
        ),
    ]
