# Generated by Django 5.1.3 on 2024-12-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='catégorie',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
