# Generated by Django 5.1.3 on 2024-12-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_populate_verification_tokens'),
        ('newtache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_remaining', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Design', 'Design'), ('Sport', 'Sport'), ('Web Dev', 'Web Dev'), ('Other', 'Other')], default='Other', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity', to='accounts.user')),
            ],
        ),
    ]
