# Generated by Django 5.1.3 on 2024-12-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtache', '0002_productivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productivity',
        ),
    ]
